# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: bolsa_emprego_development
  pool: 5
  username: bolsa_emprego
  password: 123456AZ

test:
  adapter: postgresql
  encoding: unicode
  database: bolsa_emprego_test
  pool: 5
  username: bolsa_emprego
  password: 123456AZ

production:
  adapter: postgresql
  encoding: unicode
  database: bolsa_emprego_test
  pool: 5
  username: bolsa_emprego
  password: 123456AZ
